[pyprland]
plugins = ["scratchpads","magnify"]

[scratchpads.term]
animation = "fromTop"
command = "alacritty --class=terminal"
margin = 50

[scratchpads.chrome]
animation = "fromTop"
command = "google-chrome-stable --class=browser"
margin = 50

